site_name: MCPBot
site_url: https://gkenios.github.io/mcpbot
repo_name: gkenios/mcpbot
repo_url: https://github.com/gkenios/mcpbot
theme:
  name: material
  # logo: assets/mcpbot.png
  # favicon: assets/mcpbot.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: amber
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: amber
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  features:
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

markdown_extensions:
  # Python Markdown
  - abbr:
  - attr_list:
  - footnotes:
  - md_in_html:
  - tables:
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.betterem:
  - pymdownx.caret:
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.mark:
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde:
  - pymdownx.tasklist:
      custom_checkbox: true

  # pymdownx blocks
  - pymdownx.blocks.admonition:
      types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      # Custom types
      - info
      - check
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: True

  # Other
  - def_list:


plugins:
  - search
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
            - griffe_fieldz
            docstring_style: sphinx
            show_root_heading: true
            show_if_no_docstring: false # true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
            - '!^_'
            merge_init_into_class: true
            docstring_section_style: table # spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
