[project]
name = "mcpbot"
version = "0.1.0"
description = "An implementation of an MCP client and server, using FastAPI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-cosmos>=4.9.0",
    "azure-identity>=1.21.0",
    "azure-keyvault-secrets>=4.9.0",
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "langchain-core>=0.3.56",
    "langchain-mcp-adapters>=0.0.9",
    "langchain-openai>=0.3.14",
    "langgraph>=0.3.34",
    "mcp>=1.6.0",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "pytz>=2025.2",
    "types-pytz>=2025.2.0.20250326",
]

[project.optional-dependencies]
local = [
    "langchain-chroma>=0.2.3",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "ruff>=0.11.7",
    "types-pyyaml>=6.0.12.20250402",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.12",
    "mkdocstrings-python>=1.16.10",
    "termynal>=0.13.0",
]
tests = [
    "pytest>=8.3.5",
]


[tool.ruff]
line-length = 80

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv]
default-groups = []
