name: Python Setup
description: |
  Sets up the specified python version and
  installs the necessary dependencies.

inputs:
  python-version:
    required: true
    description: Python version in the format of "3.x".
  requirements-group:
    required: false
    description: The dependency group to the python requirements text file.
    default: "null"

runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v5

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version-file: .python-version

  - name: Install dependencies
    shell: bash
    run: |
      if [ "${{ inputs.requirements-group }}" == "null" ]; then
        uv sync
      elif [ "${{ inputs.requirements-group }}" == "all" ]; then
        uv sync --all-groups
      else
        uv sync --group ${{ inputs.requirements-group }}
      fi

  - name: Activate virtual environment
    shell: bash
    run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
