auth: local

databases:
  chat:
    endpoint: ./.chatdb
    collections:
      conversations: conversations
      messages: messages
  vector:
    endpoint: ./.chromadb
    collections:
      faq: faq

models:
  embeddings:
    api_key: "{{ embeddings_key }}"  # "{{ <secret> }}" references a secret by name
    api_url: https://openai-devoteam.openai.azure.com/
    api_version: "2024-06-01"  # Optional parameter
    model: text-embedding-ada-002
  llm:
    api_key: "{{ llm_key }}"
    api_url: https://openai-devoteam.openai.azure.com/
    api_version: "2024-06-01"
    model: gpt-4o-mini

secrets:
  hosts:  # Host names in [local, azure]. Local reads from environment variables
  - name: local
    vaults:
    - name: null
      secrets:
      - name: embeddings_key  # Secret name in the application
        value: LLM            # Secret name in the vault
      - name: joan_client_id
        value: JOANID
      - name: joan_client_secret
        value: JOANSECRET
      - name: joan_company_id
        value: JOANCOMPANYID
      - name: llm_key
        value: LLM
      - name: access_token_key
        value: ACCESSTOKENKEY
      - name: refresh_token_key
        value: REFRESHTOKENKEY
